version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=boolean-model-db
      - MYSQL_ROOT_PASSWORD=sumysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - db_data:/var/lib/mysql
volumes:
  db_data: {}