version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pokemon_db
    volumes:
      - pokemon_data:/var/lib/postgresql/data
volumes:
  pokemon_data: {}